theme: jekyll-theme-cayman

title: "BebopNet: Deep Neural Models for Personalized Jazz Improvisations"
description: Shunit Haviv Hakimi, Nadav Bhonker, Ran El-Yaniv
Published in Proceedings of 21st International Society of Music Information Retrieval Conference, ISMIR 2020
show_downloads: false

github:
  is_project_page: false
